default: &default
  adapter: postgresql
  encoding: unicode
  pool: 27

development:
  <<: *default
  database: blog_development
  username: blog
  password: blog
  host: localhost
  port: 5432

test:
  <<: *default
  database: blog_test
  username: blog
  password: blog
  host: localhost
  port: 5432

